# Generated by Django 5.0.6 on 2024-06-25 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertising",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="название")),
                ("description", models.TextField(verbose_name="описание")),
                ("duration", models.DurationField(default=datetime.timedelta(days=7))),
            ],
            options={
                "verbose_name": "реклама",
            },
        ),
    ]
