# Generated by Django 5.0.6 on 2024-06-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertising",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="advertising"),
        ),
    ]
