# Generated by Django 5.0.6 on 2024-06-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0002_advertising_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertising",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="advertisings"),
        ),
    ]
