# Generated by Django 5.0.6 on 2024-06-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="blogs", verbose_name="превью"
            ),
        ),
    ]
