# Generated by Django 5.0.6 on 2024-06-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_blog_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="slug"
            ),
        ),
    ]
