# Generated by Django 5.0.6 on 2024-07-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_blog_owner_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "permissions": [
                    ("set_published_status", "Может редактировать статус публикации")
                ],
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
            },
        ),
    ]
